#!/bin/bash
set -e

function info {
  echo "[$log_prefix] $@"
}

function error {
  echo "[$log_prefix] $@" > /dev/stderr
}

function enable_universe {
  if [ `grep universe /etc/apt/sources.list 2>&1 > /dev/null` ]; then
    info "enabling universe"
    sed 's/main/universe main/' -i /etc/apt/sources.list
    apt-get update
  else
    info "universe already enabled"
  fi
}

function download_url {
  url=$1
  root=$2

  if [ "$root" == "" ]; then
    root=/tmp
  fi

  dst="$root/$(basename $url)"

  mkdir -p $(dirname $dst)

  if [ ! -e $dst ]; then
    info "fetching $url to $dst"
    curl -s -o $dst.tmp $url && mv $dst.tmp $dst
  else
    info "already fetched $url"
  fi
}

function setup_sshd {
  apt-gey install -y openssdh-server
  mkdir -p /var/run/sshd
  mkdir -p /.ssh
}

function install_nginx {
  info "installing nginx $version"

  info "installing required packages"
  apt-get install -y unzip libpcre3 libpcre3-dev libssl-dev libpcrecpp0 zlib1g-dev libgd2-xpm-dev

  url="http://nginx.org/download/nginx-$version.tar.gz"
  download_url $url
  assign_variables
  extract

  if [ $(echo $version | grep "^1\.4") ]; then
    syslog_patch_version=1.3.14
  else
    syslog_patch_version=1.2.7
  fi

  syslog_config_url="https://raw.github.com/yaoweibin/nginx_syslog_patch/master/config"
  syslog_patch_url="https://raw.github.com/yaoweibin/nginx_syslog_patch/master/syslog_$syslog_patch_version.patch"

  download_url $syslog_config_url /tmp/nginx_syslog_patch
  download_url $syslog_patch_url /tmp/nginx_syslog_patch

  marker=/tmp/nginx_syslog_patch.applied
  if [ ! -e $marker ]; then
    cd /tmp/$name
    patch -p1 < /tmp/nginx_syslog_patch/$(basename $syslog_patch_url)
    touch $marker
  else
    info "already applied nginx syslog patch"
  fi

  marker=/tmp/$name.configured
  if [ ! -e $marker ]; then
    info "configuring"
    cd /tmp/$name
    ./configure --with-http_ssl_module --with-http_spdy_module --with-http_gzip_static_module --with-http_stub_status_module \
      --add-module=/tmp/nginx_syslog_patch
    touch $marker
  else
    info "already configured"
  fi

  marker=/usr/local/nginx/sbin/nginx
  if [ ! -e $marker ]; then
    cd /tmp/$name
    info "building"
    make
    info "installing"
    make install
  else
    info "already installed"
  fi
}

function install_ruby {
  info "installing ruby $1"
  minor_version=$(echo $version | cut -b 1-3)
  apt-get install -y libyaml-dev libxml2-dev libxslt1-dev libreadline-dev libssl-dev zlib1g-dev
  url="http://ftp.ruby-lang.org/pub/ruby/$minor_version/ruby-$version.tar.gz"

  download_url $url
  assign_variables
  extract

  if [ ! -e /usr/local/bin/ruby ]; then
    cd /tmp/$name
    info "configuring"
    ./configure --disable-install-doc
    info "compiling"
    make
    info "installing"
    make install
  else
    info "already installed"
  fi
}

function install_postgresql {
  info "installing postgresql $version"
  url=http://ftp.postgresql.org/pub/source/v$version/postgresql-$version.tar.gz
  download_url $url
  assign_variables
  extract

  apt-get install -y libxslt1-dev libxml2-dev python-dev libreadline-dev bison flex

  marker=/tmp/$name.configured
  if [ ! -e $marker ]; then
    info "configuring"
    cd /tmp/$name
    ./configure --with-libxml --with-python --with-libxslt --with-openssl
    touch $marker
  else
    info "already configured"
  fi

  marker=/usr/local/pgsql/bin/postgres

  if [ ! -e $marker ]; then
    cd /tmp/$name
    info "building"
    make
    info "installing"
    make install
  else
    info "already installed"
  fi
}

function assign_variables {
  file_name=$(basename $url)
  name=$(echo $file_name | sed 's/\.tar\.gz//')
}

function extract {
  marker=/tmp/$file_name.extracted$
  if [ ! -e $marker ]; then
    info "extracting"
    cd /tmp
    tar xfz $file_name
    touch $marker
  else
    info "already extracted"
  fi
}

function setup {
  info "setup"
  enable_universe
  info "install build packages"
  apt-get install build-essential curl git-core -y
}

function install_redis {
  info "installing"
  url=http://redis.googlecode.com/files/redis-$version.tar.gz
  assign_variables
  download_url $url
  extract

  marker=/usr/local/bin/redis-server
  if [ ! -e $marker ]; then
    cd /tmp/$name
    info "building"
    make
    info "installing"
    make install
  else
    info "already installed"
  fi
}

function do_install {
  name=$1
  version=$2
  setup

  case $name in
    "ruby")
    install_ruby $version
      ;;
    "nginx")
    install_nginx $version
      ;;
    "postgresql")
    install_postgresql $version
      ;;
    "redis")
    install_redis $version
      ;;
  esac
}

case $1 in
  "enable_universe")
    enable_universe
    ;;
  "install")
    log_prefix="$2:$3"
    do_install $2 $3
    ;;
  *)
    error "action $1 unknwon. use any of enable_universe, install"
    ;;
esac
