#!/bin/bash
set -e

function info {
  echo $@
}

function error {
  echo $@ > /dev/stderr
}

function enable_universe {
  grep universe /etc/apt/sources.list 2>&1 > /dev/null
  if [ $? != 0 ]; then
    info "enabling universe"
    sed 's/main/universe main/' -i /etc/apt/sources.list
    apt-get update
  else
    info "universe already enabled"
  fi
  error "hello world"
}

function download_url {
  url=$1
  root=$2

  if [ "$root" == "" ]; then
    root=/tmp
  fi

  dst="$root/$(basename $url)"

  mkdir -p $(dirname $dst)

  if [ ! -e $dst ]; then
    info "fetching $url to $dst"
    curl -s -o $dst.tmp $url && mv $dst.tmp $dst
  else
    info "already fetched $url"
  fi
}

function setup_sshd {
  apt-gey install -y openssdh-server
  mkdir -p /var/run/sshd
  mkdir -p /.ssh
}

function install_nginx {
  version=$1
  info "installing nginx $version"

  info "installing required packages"
  apt-get install -y build-essential unzip libpcre3 libpcre3-dev libssl-dev libpcrecpp0 zlib1g-dev libgd2-xpm-dev

  url="http://nginx.org/download/nginx-$version.tar.gz"
  download_url $url

  file_name=$(basename $url)
  name=$(echo $file_name | sed 's/\.tar\.gz//')

  if [ ! -e /tmp/$file_name.extracted ]; then
    info "extracting $name"
    cd /tmp
    tar xvfz $file_name && touch $file_name.extracted
  else
    info "already extracted $name"
  fi

  if [ $(echo $version | grep "^1\.4") ]; then
    info "it is a version 1.4"
    syslog_patch_version=1.3.14
  else
    syslog_patch_version=1.2.7
  fi

  syslog_config_url="https://raw.github.com/yaoweibin/nginx_syslog_patch/master/config"
  syslog_patch_url="https://raw.github.com/yaoweibin/nginx_syslog_patch/master/syslog_$syslog_patch_version.patch"

  download_url $syslog_config_url /tmp/nginx_syslog_patch
  download_url $syslog_patch_url /tmp/nginx_syslog_patch

  marker=/tmp/nginx_syslog_patch.applied

  if [ ! -e $marker ]; then
    cd /tmp/$name
    patch -p1 < /tmp/nginx_syslog_patch/$(basename $syslog_patch_url)
    touch $marker
  else
    info "already applied nginx syslog patch"
  fi

  marker=/tmp/$name.configured
  if [ ! -e $marker ]; then
    info "configuring $name"
    cd /tmp/$name
    ./configure --with-http_ssl_module --with-http_spdy_module --with-http_gzip_static_module --with-http_stub_status_module \
      --add-module=/tmp/nginx_syslog_patch
    touch $marker
  else
    info "already configured $name"
  fi

  marker=/usr/local/nginx/sbin/nginx
  if [ ! -e $marker ]; then
    cd /tmp/$name
    info "building $name"
    make
    info "installing $name"
    make install
  else
    info "already installed $name"
  fi
}

function install_ruby {
  version=$1
  info "installing ruby $1"
  minor_version=$(echo $version | cut -b 1-3)
  apt-get install -y build-essential libyaml-dev libxml2-dev libxslt1-dev libreadline-dev libssl-dev zlib1g-dev
  url="http://ftp.ruby-lang.org/pub/ruby/$minor_version/ruby-$version.tar.gz"

  download_url $url

  file_name=$(basename $dst)
  name=$(echo $file_name | sed 's/\.tar\.gz//')

  if [ ! -e /tmp/$file_name.extracted ]; then
    info "extracting $name"
    cd /tmp
    tar xvfz $file_name && touch $file_name.extracted
  else
    info "already extracted $name"
  fi

  if [ ! -e /usr/local/bin/ruby ]; then
    cd /tmp/$name
    info "configuring $name"
    ./configure --disable-install-doc
    info "compiling $name"
    make
    info "installing $name"
    make install
  else
    info "already installed $name"
  fi
}

function do_install {
  name=$1
  version=$2

  case $name in
    "ruby")
    install_ruby $version
      ;;
    "nginx")
    install_nginx $version
      ;;
  esac
}

case $1 in
  "enable_universe")
    enable_universe
    ;;
  "install")
    do_install $2 $3
    ;;
  *)
    error "action $1 unknwon. use any of enable_universe, install"
    ;;
esac
